language: ruby

rvm:
  - 2.0.0
  - 2.1.2

env:
  - PUPPET_VERSION=3.4.3
  - PUPPET_VERSION=3.6.2

before_install: 
  - true

script:
  - for F in $(find templates -type f -iname "*.erb"); do bundle exec erb -P -x -T '-' $F | ruby -c; done
  - bundle exec puppet parser validate manifests/*.pp
