language: ruby

rvm: 
  - 1.8.7
  - 1.9.2
  - 1.9.3

env:
  - PUPPET_VERSION=2.7.11
  - PUPPET_VERSION=3.4.2

before_install: 
  - true

script:
  - bundle exec rake lint
  - bundle exec puppet parser validate
